### ISSUE TITLE
Issue when installing openkb in CentOS 6.6

### ISSUE THREAD

**Issue by Djas2017** [mrvautin/openKB#131]
Hi,
Error when installing in CentOS 6.6.

`# npm start
> openkb@1.0.18 start /root/openKB/openKB
> node app.js
/root/openKB/openKB/routes/index.js:1424
ddir(path.join(__dirname, '..', 'public', 'temp', 'import'), (err, files) => {
                                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/openKB/openKB/app.js:24:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm ERR! not ok code 0`

**Comment by mrvautin** [comment]
What version of Node.js do you have installed? Needs to be v4.x or above.

`node -v`

**Comment by Djas2017** [comment]
`# node -v
v0.10.48`

**Comment by mrvautin** [comment]
You will need to update as that version is extremely old. Update guide is [here](https://nodejs.org/en/download/package-manager/).

**Comment by Djas2017** [comment]
Got it! Thanks
Installed a newer version of Node.js by following your guide and the openkb is now working on my Centos.

Question:
Is there any guide which explains how to install openkb in a cPanel shared hosting?

**Comment by mrvautin** [comment]
It's best to contact the shared hosting provider for instructions on installing Nodejs as it can differ depending on the hosting providers setup.
