### ISSUE TITLE
Crashes when trying upload a file

### ISSUE THREAD

**Issue by JamesTimms** [mrvautin/openKB#134]
Hi there,

Found this project today and thought I'd give it a go, am liking it so far. While playing around I found an issue I thought might be worth reporting. Running app on Master (73c39b).

When trying to upload a file on /files view it crashes with the below error message. I've managed to reproduced this error across npm & node versions and using a .pdf and a .docx file. The file appears to upload successfully but crashes after the upload has been completed, also occurs when deleting a file. 
The file name I tested with was "324234 - YTU dsfsdfsdfsd - RTR v1.2 ER TY v2" .pdf or .docx depending on file trying to upload. Tried uploading file on /uploads and /uploads/documents.

If you need any more info please let me know.

James

```
$ npm start

\>openkb@1.0.19 start _[base_dir]_\openKB
\>node app.js

openKB running on host: http://127.0.0.1:4444
GET / 304 163.036 ms - -
GET /stylesheets/flatly.bootstrap.min.css 304 24.306 ms - -
GET /stylesheets/style.css 304 19.057 ms - -
GET /simplemde/simplemde.min.css 304 34.453 ms - -
GET /stylesheets/github.css 304 46.299 ms - -
GET /font-awesome/css/font-awesome.min.css 304 50.987 ms - -
GET /stylesheets/mermaid.css 304 27.601 ms - -
GET /stylesheets/jasny-bootstrap.min.css 304 28.190 ms - -
GET /stylesheets/jpushmenu.css 304 32.325 ms - -
GET /jquery/jquery.min.js 304 31.291 ms - -
GET /bootstrap/js/bootstrap.min.js 304 29.286 ms - -
GET /stylesheets/bootstrap-tokenfield.css 304 50.503 ms - -
GET /javascripts/bootstrap-validator.js 304 32.434 ms - -
GET /javascripts/bootstrap-tokenfield.min.js 304 27.805 ms - -
GET /javascripts/inline-attachment.js 304 26.632 ms - -
GET /javascripts/codemirror.inline-attachment.js 304 26.235 ms - -
GET /javascripts/markdown-it-classy.js 304 45.107 ms - -
GET /javascripts/highlight.min.js 304 32.092 ms - -
GET /simplemde/simplemde.min.js 304 21.960 ms - -
GET /javascripts/jasny-bootstrap.min.js 304 24.509 ms - -
GET /javascripts/loadingoverlay.min.js 304 41.330 ms - -
GET /lunr/lunr.min.js 304 25.831 ms - -
GET /markdown-it/markdown-it.min.js 304 32.754 ms - -
GET /javascripts/jpushmenu.js 304 25.346 ms - -
GET /javascripts/openKB.js 304 21.690 ms - -
GET /logo.png 304 4.100 ms - -
POST /search_api 200 28.687 ms - -
GET /favicon.png 200 20.572 ms - 2041
GET /font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 304 4.285 ms - -
GET /files 200 103.711 ms - -
GET /stylesheets/flatly.bootstrap.min.css 304 9.344 ms - -
GET /simplemde/simplemde.min.css 304 11.914 ms - -
GET /stylesheets/github.css 304 13.824 ms - -
GET /stylesheets/style.css 304 13.099 ms - -
GET /font-awesome/css/font-awesome.min.css 304 23.892 ms - -
GET /stylesheets/mermaid.css 304 24.427 ms - -
GET /stylesheets/bootstrap-tokenfield.css 304 27.576 ms - -
GET /stylesheets/jasny-bootstrap.min.css 304 33.963 ms - -
GET /stylesheets/jpushmenu.css 304 39.323 ms - -
GET /jquery/jquery.min.js 304 39.870 ms - -
GET /bootstrap/js/bootstrap.min.js 304 34.625 ms - -
GET /javascripts/bootstrap-validator.js 304 39.528 ms - -
GET /javascripts/bootstrap-tokenfield.min.js 304 30.840 ms - -
GET /javascripts/markdown-it-classy.js 304 43.426 ms - -
GET /javascripts/codemirror.inline-attachment.js 304 33.972 ms - -
GET /javascripts/inline-attachment.js 304 48.843 ms - -
GET /javascripts/highlight.min.js 304 41.655 ms - -
GET /javascripts/loadingoverlay.min.js 304 43.782 ms - -
GET /simplemde/simplemde.min.js 304 43.972 ms - -
GET /javascripts/jasny-bootstrap.min.js 304 42.596 ms - -
GET /markdown-it/markdown-it.min.js 304 45.950 ms - -
GET /lunr/lunr.min.js 304 41.855 ms - -
GET /javascripts/jpushmenu.js 304 37.466 ms - -
GET /javascripts/openKB.js 304 33.833 ms - -
GET /logo.png 304 11.481 ms - -
GET /font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 304 3.241 ms - -
POST /file/upload 302 85.334 ms - 56
fs.js:982
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '_[base_dir]_\openKB\public\uploads\b8a2da6f6aa7874319c9e0d0a7d02567'
    at Error (native)
    at Object.fs.lstatSync (fs.js:982:18)
    at _[base_dir]_\openKB\routes\index.js:1243:10
    at f (_[base_dir]_\openKB\node_modules\once\once.js:25:25)
    at Glob.<anonymous> (_[base_dir]_\openKB\node_modules\glob\glob.js:133:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob.\_finish (_[base_dir]_\openKB\node_modules\glob\glob.js:172:8)
    at done (_[base_dir]_\openKB\node_modules\glob\glob.js:159:12)
    at Glob.\_processGlobStar2 (_[base_dir]_\openKB\node_modules\glob\glob.js:601:12)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\_[user]_\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openkb@1.0.19 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openkb@1.0.19 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openkb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openkb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openkb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\_[user]_\AppData\Roaming\npm-cache\_logs\2017-02-14T17_18_14_166Z-debug.log
```

**Comment by mrvautin** [comment]
I can see you are running Windows. Unfortunately I dont have a Windows machine to confirm the error. I've put in an additional check to see whether the file/directory exists before checking if its a file or directory (I hope that makes sense). I assume that there is some funny business with node-glob picking up some non existant files/directories on Windows. 

Anyway, I really hope this fixes otherwise I might need someone else to try find the issue who has access to a Windows computer. Do you have this issue @thedaftbadger?

**Comment by JamesTimms** [comment]
Tried out the changes and it appears they have fixed the bug :) Should be ok to close this. Thanks for the quick response!

**Comment by mrvautin** [comment]
👍

**Comment by thedaftbadger** [comment]
@mrvautin Sorry been busy :( I will test this release on my 2 windows server environments tomorrow and report back.
