### ISSUE TITLE
Latest version slower over nginx

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#138]
Anyone else noticed that the latest release is a lot slower than previous builds? 🤔 

Running over Nginx and PM2.

**Comment by mrvautin** [comment]
It's running on nginx + pm2 [here](http://openkb.mrvautin.com). Do you think it's also slow?

**Comment by thedaftbadger** [comment]
Yeh compared to an old version I have running (yet to be upgraded) it is taking ages to load.

**Comment by thedaftbadger** [comment]
Just noticed this....

```
3|AdminKB  | Error: Not Found
3|AdminKB  |     at c:\adminkb\app.js:241:15
3|AdminKB  |     at Layer.handle [as handle_request] (c:\adminkb\node_modules\express\lib\router\layer.js:82:5)
3|AdminKB  |     at trim_prefix (c:\adminkb\node_modules\express\lib\router\index.js:270:13)
3|AdminKB  |     at c:\adminkb\node_modules\express\lib\router\index.js:237:9
3|AdminKB  |     at Function.proto.process_params (c:\adminkb\node_modules\express\lib\router\index.js:312:12)
3|AdminKB  |     at c:\adminkb\node_modules\express\lib\router\index.js:228:12
3|AdminKB  |     at Function.match_layer (c:\adminkb\node_modules\express\lib\router\index.js:295:3)
3|AdminKB  |     at next (c:\adminkb\node_modules\express\lib\router\index.js:189:10)
3|AdminKB  |     at c:\adminkb\node_modules\express\lib\router\index.js:560:15
3|AdminKB  |     at next (c:\adminkb\node_modules\express\lib\router\index.js:186:14)
```

**Comment by mrvautin** [comment]
Weird. That error log is just a 404 page not found error. 

If you notice anything else, let me know.

**Comment by thedaftbadger** [comment]
@mrvautin Very strange, permissions for the whole app folder are set to "Everyone" so I doubt it's a permissions issue.

**Comment by thedaftbadger** [comment]
Not finding any major issues. I think I had an issue with my node and nginx version.
