### ISSUE TITLE
`COPY config/ /var/openKB/config/` in the `Dockerfile`?

### ISSUE THREAD

**Issue by judexzhu** [mrvautin/openKB#188]
Excuse me , did you miss  `COPY config/ /var/openKB/config/` in the `Dockerfile`?

```
FROM alpine:3.5

RUN apk add --update nodejs

WORKDIR /var/openKB

COPY locales/ /var/openKB/locales/
COPY public/ /var/openKB/public/
COPY routes/ /var/openKB/routes/
COPY views/ /var/openKB/views/
COPY app.js /var/openKB/
COPY package.json /var/openKB/

RUN npm install

VOLUME /var/openKB/data

EXPOSE 4444
ENTRYPOINT ["npm", "start"]
```
logs:
```
> openkb@1.0.22 start /var/openKB
> node app.js
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/var/openKB/config/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.exports.read_config (/var/openKB/routes/common.js:32:22)
    at Object.<anonymous> (/var/openKB/app.js:16:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Linux 3.10.0-514.21.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! openkb@1.0.22 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openkb@1.0.22 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openkb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openkb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openkb
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /var/openKB/npm-debug.log
```

**Comment by mrvautin** [comment]
Thanks. Added in: 2c6e3250a44caf97fa20680ca371b649f38abd39.

**Comment by judexzhu** [comment]
Just saw you did it , my pleasure.
