### ISSUE TITLE
weird error 8

### ISSUE THREAD

**Issue by sinu** [mrvautin/openKB#207]
Could you please tell me how to resolve this

```
/var/tmp/openKB/routes/index.js:1473
ddir(path.join(__dirname, '..', 'public', 'temp', 'import'), (err, files) => {
                                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/tmp/openKB/app.js:22:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm ERR! not ok code 0

```

**Comment by mrvautin** [comment]
You need to upgrade Node.js. You are running a really old version.

**Comment by sinu** [comment]
Thanks yes its fixed
