### ISSUE TITLE
Error: More than 10% of the data file is corrupt.

### ISSUE THREAD

**Issue by GAZ082** [mrvautin/openKB#254]
```
Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
    at Persistence.treatRawData (/var/www/public/xxxx/openKB/node_modules/nedb/lib/persistence.js:242:11)
    at /var/www/public/xxxx/openKB/node_modules/nedb/lib/persistence.js:281:38
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

Hi! Cant restart the service, what can i do? Thanks!

**Comment by mrvautin** [comment]
You can turn the monitor in off and/or delete the data file and let it be created again.
