### ISSUE TITLE
mongodb support Broken

### ISSUE THREAD

**Issue by git-minix** [mrvautin/openKB#255]
```
Started openKB ...
undefined:28
            "connection_string": "mongodb://127.0.0.1:27017/openkb"
            ^

SyntaxError: Unexpected string in JSON at position 864
    at Object.parse (native)
    at Object.exports.read_config (/opt/openKB/routes/common.js:33:29)
    at Object.<anonymous> (/opt/openKB/app.js:16:21)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
```

config.json:
```
        "database": {
            "type": "mongodb"
            "connection_string": "mongodb://127.0.0.1:27017/openkb"
        },
```

openKB works fine with the embedded database

```
        "database": {
            "type": "embedded"
        },
```

**Comment by jfemia** [comment]
You have invalid JSON in your config file. Put a comma after the database type.

  "type": "mongodb",

**Comment by mrvautin** [comment]
Yep. Missing comma.
