### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by Wachiwi** [mrvautin/openKB#31]
It seems the app wants to access a directory outside the working directory. I just cloned the repo, ran `npm install` and wanted to start it via `npm start`. If you need further information let me know. 

```
/var/openKB/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/public'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at sync (/var/openKB/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/var/openKB/node_modules/mkdirp/index.js:77:24)
    at new DiskStorage (/var/openKB/node_modules/multer/storage/disk.js:21:12)
    at module.exports (/var/openKB/node_modules/multer/storage/disk.js:65:10)
    at new Multer (/var/openKB/node_modules/multer/index.js:15:20)
    at multer (/var/openKB/node_modules/multer/index.js:75:12)
    at Object.<anonymous> (/var/openKB/routes/index.js:608:14)
    at Module._compile (module.js:435:26)
```

**Comment by mrvautin** [comment]
Ah yes. At a quick look it appears I'm missing a leading slash in /routes/index.js on line 587. I will test further and fix.

**Comment by mrvautin** [comment]
Had a look further. Issue is related to server permissions to the file. User running the node instance needs permissions to create a directory in /public/ where /public/uploads/<dir name> will be created. Happy to look at it further it anyone thinks otherwise.
