### ISSUE TITLE
Search 404 within article

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#4]
If I try to use the "Search" bar whilst within an article returns a `404 Not Found` error.
Searching using the same term on the front page works fine.

```
Not Found
404
Error: Not Found
    at c:\xampp\htdocs\openkb\app.js:113:15
    at Layer.handle [as handle_request] (c:\xampp\htdocs\openkb\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (c:\xampp\htdocs\openkb\node_modules\express\lib\router\index.js:270:13)
    at c:\xampp\htdocs\openkb\node_modules\express\lib\router\index.js:237:9
    at Function.proto.process_params (c:\xampp\htdocs\openkb\node_modules\express\lib\router\index.js:312:12)
    at c:\xampp\htdocs\openkb\node_modules\express\lib\router\index.js:228:12
    at Function.match_layer (c:\xampp\htdocs\openkb\node_modules\express\lib\router\index.js:295:3)
    at next (c:\xampp\htdocs\openkb\node_modules\express\lib\router\index.js:189:10)
    at c:\xampp\htdocs\openkb\node_modules\express\lib\router\index.js:560:15
    at next (c:\xampp\htdocs\openkb\node_modules\express\lib\router\index.js:186:14)
```

**Comment by mrvautin** [comment]
Fixed: 3e067c7f2fca2b43e6f17f8fd7522a78e2df1bff
