### ISSUE TITLE
Bug: crash on save

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#48]
```
TypeError: Cannot read property 'type' of undefined
    at getClassyFromInlineToken (/home/webuser/adminkb/node_modules/markdown-it-classy/index.js:114:30)
    at Array.parseBlock (/home/webuser/adminkb/node_modules/markdown-it-classy/index.js:166:16)
    at Core.process (/home/webuser/adminkb/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/home/webuser/adminkb/node_modules/markdown-it/lib/index.js:493:13)
    at MarkdownIt.render (/home/webuser/adminkb/node_modules/markdown-it/lib/index.js:513:36)
    at /home/webuser/adminkb/routes/index.js:87:28
    at newArguments.(anonymous function) (/home/webuser/adminkb/node_modules/nedb/lib/executor.js:29:17)
    at /home/webuser/adminkb/node_modules/nedb/lib/datastore.js:642:18
    at /home/webuser/adminkb/node_modules/nedb/lib/persistence.js:201:12
    at FSReqWrap.oncomplete (fs.js:82:15)
TypeError: Cannot read property 'type' of undefined
    at getClassyFromInlineToken (/home/webuser/adminkb/node_modules/markdown-it-classy/index.js:114:30)
    at Array.parseBlock (/home/webuser/adminkb/node_modules/markdown-it-classy/index.js:166:16)
    at Core.process (/home/webuser/adminkb/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/home/webuser/adminkb/node_modules/markdown-it/lib/index.js:493:13)
    at MarkdownIt.render (/home/webuser/adminkb/node_modules/markdown-it/lib/index.js:513:36)
    at /home/webuser/adminkb/routes/index.js:87:28
    at newArguments.(anonymous function) (/home/webuser/adminkb/node_modules/nedb/lib/executor.js:29:17)
    at /home/webuser/adminkb/node_modules/nedb/lib/datastore.js:642:18
    at /home/webuser/adminkb/node_modules/nedb/lib/persistence.js:201:12
    at FSReqWrap.oncomplete (fs.js:82:15)
TypeError: Cannot read property 'type' of undefined
    at getClassyFromInlineToken (/home/webuser/adminkb/node_modules/markdown-it-classy/index.js:114:30)
    at Array.parseBlock (/home/webuser/adminkb/node_modules/markdown-it-classy/index.js:166:16)
    at Core.process (/home/webuser/adminkb/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/home/webuser/adminkb/node_modules/markdown-it/lib/index.js:493:13)
    at MarkdownIt.render (/home/webuser/adminkb/node_modules/markdown-it/lib/index.js:513:36)
    at /home/webuser/adminkb/routes/index.js:87:28
    at newArguments.(anonymous function) (/home/webuser/adminkb/node_modules/nedb/lib/executor.js:29:17)
    at /home/webuser/adminkb/node_modules/nedb/lib/datastore.js:642:18
    at Persistence.persistNewState (/home/webuser/adminkb/node_modules/nedb/lib/persistence.js:198:40)
    at /home/webuser/adminkb/node_modules/nedb/lib/datastore.js:639:24
TypeError: Cannot read property 'type' of undefined
    at getClassyFromInlineToken (/home/webuser/adminkb/node_modules/markdown-it-classy/index.js:114:30)
    at Array.parseBlock (/home/webuser/adminkb/node_modules/markdown-it-classy/index.js:166:16)
    at Core.process (/home/webuser/adminkb/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/home/webuser/adminkb/node_modules/markdown-it/lib/index.js:493:13)
    at MarkdownIt.render (/home/webuser/adminkb/node_modules/markdown-it/lib/index.js:513:36)
    at /home/webuser/adminkb/routes/index.js:87:28
    at newArguments.(anonymous function) (/home/webuser/adminkb/node_modules/nedb/lib/executor.js:29:17)
    at /home/webuser/adminkb/node_modules/nedb/lib/datastore.js:642:18
    at /home/webuser/adminkb/node_modules/nedb/lib/persistence.js:201:12
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by thedaftbadger** [comment]
Only crashes when a markdown table is added to an article, like this....

| Site | Provider | IP | Subnet Mask |
|------------|----------|----|-------------|
| Site 1 | Telco|  |  |
| Site 2 | Telco |  |  |
| Site 3 | Telco |  |  |
| Site 4 | Telco |  |  |
| Site 5 | Telco |  |  |

```
| Site | Provider | IP | Subnet Mask |
|------------|----------|----|-------------|
| Site 1 | Telco|  |  |
| Site 2 | Telco |  |  |
| Site 3 | Telco |  |  |
| Site 4 | Telco |  |  |
| Site 5 | Telco |  |  |
```

**Comment by mrvautin** [comment]
That error is from the markdown module and not `openKB`. I will try replicate and see if there is a fix.

**Comment by mrvautin** [comment]
Found issue is in the `markdown-it-classy` module. Submitted fix in PR here: https://github.com/andrey-p/markdown-it-classy/pull/9

The repo has not had much activity for some time. If the PR is merged I will bump the NPM version, else I will look to package it into `openKB`.

**Comment by thedaftbadger** [comment]
Ok, sounds good. Found that the last release (of openkb)  is causing both my apps to constantly restart in PM2

**Comment by mrvautin** [comment]
That's not good. Are they only restarting because of this bug or another there are other bugs?

**Comment by thedaftbadger** [comment]
Not 100% sure tbh, I am new to PM2 as a whole. Any particular log I should be looking at?

**Comment by mrvautin** [comment]
PM2 is great. You can run `pm2 logs` to get all logs or `pm2 logs 2` (where two is the app number/index) to get specific logs for that app.

**Comment by thedaftbadger** [comment]
Looking now. Will report back in a few mins

**Comment by thedaftbadger** [comment]
Only error I can see now is that it only crashes when I create an article with a table and then try and view it....

### App 1 Crash Log (viewing newly created table)
```
Admin_KB-1 TypeError: Cannot read property 'type' of undefined
Admin_KB-1     at getClassyFromInlineToken (/home/webuser/adminkb/node_modules/markdown-it-classy/index.js:114:30)
Admin_KB-1     at Array.parseBlock (/home/webuser/adminkb/node_modules/markdown-it-classy/index.js:166:16)
Admin_KB-1     at Core.process (/home/webuser/adminkb/node_modules/markdown-it/lib/parser_core.js:51:13)
Admin_KB-1     at MarkdownIt.parse (/home/webuser/adminkb/node_modules/markdown-it/lib/index.js:493:13)
Admin_KB-1     at MarkdownIt.render (/home/webuser/adminkb/node_modules/markdown-it/lib/index.js:513:36)
Admin_KB-1     at /home/webuser/adminkb/routes/index.js:87:28
Admin_KB-1     at newArguments.(anonymous function) (/home/webuser/adminkb/node_modules/nedb/lib/executor.js:29:17)
Admin_KB-1     at /home/webuser/adminkb/node_modules/nedb/lib/datastore.js:642:18
Admin_KB-1     at Persistence.persistNewState (/home/webuser/adminkb/node_modules/nedb/lib/persistence.js:198:40)
Admin_KB-1     at /home/webuser/adminkb/node_modules/nedb/lib/datastore.js:639:24
```

### App 2 Crash Log (viewing newly created table)

```
IT_KB-0 GET /javascripts/markdown-editor.js 304 3.379 ms - -
IT_KB-0 TypeError: Cannot read property 'type' of undefined
IT_KB-0     at getClassyFromInlineToken (/home/webuser/itkb/node_modules/markdown-it-classy/index.js:114:30)
IT_KB-0     at Array.parseBlock (/home/webuser/itkb/node_modules/markdown-it-classy/index.js:166:16)
IT_KB-0     at Core.process (/home/webuser/itkb/node_modules/markdown-it/lib/parser_core.js:51:13)
IT_KB-0     at MarkdownIt.parse (/home/webuser/itkb/node_modules/markdown-it/lib/index.js:493:13)
IT_KB-0     at MarkdownIt.render (/home/webuser/itkb/node_modules/markdown-it/lib/index.js:513:36)
IT_KB-0     at /home/webuser/itkb/routes/index.js:87:28
IT_KB-0     at newArguments.(anonymous function) (/home/webuser/itkb/node_modules/nedb/lib/executor.js:29:17)
IT_KB-0     at /home/webuser/itkb/node_modules/nedb/lib/datastore.js:642:18
IT_KB-0     at /home/webuser/itkb/node_modules/nedb/lib/persistence.js:201:12
IT_KB-0     at FSReqWrap.oncomplete (fs.js:82:15)
```

Old articles with markdown tables already created view fine, without an app crash.

**Comment by mrvautin** [comment]
Ok. That is the bug I fixed. Hopefully the PR is merged asap.

**Comment by thedaftbadger** [comment]
I guess once it is merged an npm update?

**Comment by mrvautin** [comment]
A small code change is required.

**Comment by thedaftbadger** [comment]
I suspect that the PR wont be merged I have read a lot of frustration from others about it :(
