### ISSUE TITLE
Updating openKB?

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#5]
Can openKB just have files overwritten and then server started again?

**Comment by mrvautin** [comment]
Yes. I would recommend taking a full folder backup first.

**Comment by thedaftbadger** [comment]
OK cool.... apart from the config files, where are the KB articles stored?

**Comment by mrvautin** [comment]
In the /data/kb.db and users are in /data/users.db

**Comment by thedaftbadger** [comment]
do you need to run `npm install` after copying new files over?

**Comment by mrvautin** [comment]
Yes it's always a good idea. I've added some other dependencies so it's required in this case.

**Comment by thedaftbadger** [comment]
Getting a weird error from Node.js when running `npm install`

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose readDependencies loading dependencies from c:\xampp\htdocs\openkb\package.json
5 verbose install where, deps [ 'c:\\xampp\\htdocs\\openkb',
5 verbose install   [ 'bcrypt-nodejs',
5 verbose install     'body-parser',
5 verbose install     'cookie-parser',
5 verbose install     'debug',
5 verbose install     'express',
5 verbose install     'express-handlebars',
5 verbose install     'express-session',
5 verbose install     'glob',
5 verbose install     'hbs',
5 verbose install     'image-size',
5 verbose install     'marked',
5 verbose install     'morgan',
5 verbose install     'multer',
5 verbose install     'nedb',
5 verbose install     'serve-favicon' ] ]
6 verbose install where, peers [ 'c:\\xampp\\htdocs\\openkb', [] ]
7 verbose installManyTop reading for lifecycle c:\xampp\htdocs\openkb\package.json
8 info preinstall openkb@0.0.8
9 verbose installManyTop reading scoped package data from c:\xampp\htdocs\openkb\node_modules\bcrypt-nodejs\package.json
10 verbose installManyTop reading scoped package data from c:\xampp\htdocs\openkb\node_modules\body-parser\package.json
11 verbose installManyTop reading scoped package data from c:\xampp\htdocs\openkb\node_modules\cookie-parser\package.json
12 verbose installManyTop reading scoped package data from c:\xampp\htdocs\openkb\node_modules\debug\package.json
13 verbose installManyTop reading scoped package data from c:\xampp\htdocs\openkb\node_modules\express\package.json
14 verbose installManyTop reading scoped package data from c:\xampp\htdocs\openkb\node_modules\express-handlebars\package.json
15 verbose installManyTop reading scoped package data from c:\xampp\htdocs\openkb\node_modules\express-session\package.json
16 verbose installManyTop reading scoped package data from c:\xampp\htdocs\openkb\node_modules\hbs\package.json
17 verbose installManyTop reading scoped package data from c:\xampp\htdocs\openkb\node_modules\marked\package.json
18 verbose installManyTop reading scoped package data from c:\xampp\htdocs\openkb\node_modules\morgan\package.json
19 verbose installManyTop reading scoped package data from c:\xampp\htdocs\openkb\node_modules\nedb\package.json
20 verbose installManyTop reading scoped package data from c:\xampp\htdocs\openkb\node_modules\serve-favicon\package.json
21 info package.json bcrypt-nodejs@0.0.3 No license field.
22 info package.json debug@2.0.0 No license field.
23 info package.json hbs@2.7.0 No license field.
24 info package.json nedb@1.1.3 license should be a valid SPDX license expression
25 verbose readDependencies loading dependencies from c:\xampp\htdocs\openkb\package.json
26 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\bcrypt-nodejs\package.json
27 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\body-parser\package.json
28 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\cookie-parser\package.json
29 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\debug\package.json
30 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\express\package.json
31 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\express-handlebars\package.json
32 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\express-session\package.json
33 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\hbs\package.json
34 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\marked\package.json
35 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\morgan\package.json
36 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\nedb\package.json
37 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\serve-favicon\package.json
38 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\.bin\marked\package.json
39 verbose targetResolver reading package data from c:\xampp\htdocs\openkb\node_modules\.bin\marked.cmd\package.json
40 verbose already installed skipping hbs@~2.7.0 c:\xampp\htdocs\openkb
41 silly cache add args [ 'image-size@^0.3.5', null ]
42 verbose cache add spec image-size@^0.3.5
43 silly cache add parsed spec { raw: 'image-size@^0.3.5',
43 silly cache add   scope: null,
43 silly cache add   name: 'image-size',
43 silly cache add   rawSpec: '^0.3.5',
43 silly cache add   spec: '>=0.3.5 <0.4.0',
43 silly cache add   type: 'range' }
44 silly addNamed image-size@>=0.3.5 <0.4.0
45 verbose addNamed ">=0.3.5 <0.4.0" is a valid semver range for image-size
46 silly addNameRange { name: 'image-size', range: '>=0.3.5 <0.4.0', hasData: false }
47 silly mapToRegistry name image-size
48 silly mapToRegistry using default registry
49 silly mapToRegistry registry https://registry.npmjs.org/
50 silly mapToRegistry uri https://registry.npmjs.org/image-size
51 verbose addNameRange registry:https://registry.npmjs.org/image-size not in flight; fetching
52 verbose request uri https://registry.npmjs.org/image-size
53 verbose request no auth needed
54 info attempt registry request try #1 at 10:53:51 AM
55 verbose request id 98f1fcd8355d2df5
56 http request GET https://registry.npmjs.org/image-size
57 verbose already installed skipping marked@^0.3.5 c:\xampp\htdocs\openkb
58 verbose already installed skipping morgan@~1.3.0 c:\xampp\htdocs\openkb
59 silly cache add args [ 'multer@^1.0.3', null ]
60 verbose cache add spec multer@^1.0.3
61 silly cache add parsed spec { raw: 'multer@^1.0.3',
61 silly cache add   scope: null,
61 silly cache add   name: 'multer',
61 silly cache add   rawSpec: '^1.0.3',
61 silly cache add   spec: '>=1.0.3 <2.0.0',
61 silly cache add   type: 'range' }
62 silly addNamed multer@>=1.0.3 <2.0.0
63 verbose addNamed ">=1.0.3 <2.0.0" is a valid semver range for multer
64 silly addNameRange { name: 'multer', range: '>=1.0.3 <2.0.0', hasData: false }
65 silly mapToRegistry name multer
66 silly mapToRegistry using default registry
67 silly mapToRegistry registry https://registry.npmjs.org/
68 silly mapToRegistry uri https://registry.npmjs.org/multer
69 verbose addNameRange registry:https://registry.npmjs.org/multer not in flight; fetching
70 verbose already installed skipping nedb@^1.1.2 c:\xampp\htdocs\openkb
71 verbose already installed skipping serve-favicon@~2.1.3 c:\xampp\htdocs\openkb
72 verbose already installed skipping bcrypt-nodejs@0.0.3 c:\xampp\htdocs\openkb
73 verbose already installed skipping body-parser@^1.8.4 c:\xampp\htdocs\openkb
74 verbose already installed skipping cookie-parser@~1.3.3 c:\xampp\htdocs\openkb
75 verbose already installed skipping debug@~2.0.0 c:\xampp\htdocs\openkb
76 verbose already installed skipping express@~4.9.0 c:\xampp\htdocs\openkb
77 verbose already installed skipping express-handlebars@^2.0.1 c:\xampp\htdocs\openkb
78 verbose already installed skipping express-session@^1.11.3 c:\xampp\htdocs\openkb
79 silly cache add args [ 'glob@^5.0.14', null ]
80 verbose cache add spec glob@^5.0.14
81 silly cache add parsed spec { raw: 'glob@^5.0.14',
81 silly cache add   scope: null,
81 silly cache add   name: 'glob',
81 silly cache add   rawSpec: '^5.0.14',
81 silly cache add   spec: '>=5.0.14 <6.0.0',
81 silly cache add   type: 'range' }
82 silly addNamed glob@>=5.0.14 <6.0.0
83 verbose addNamed ">=5.0.14 <6.0.0" is a valid semver range for glob
84 silly addNameRange { name: 'glob', range: '>=5.0.14 <6.0.0', hasData: false }
85 silly mapToRegistry name glob
86 silly mapToRegistry using default registry
87 silly mapToRegistry registry https://registry.npmjs.org/
88 silly mapToRegistry uri https://registry.npmjs.org/glob
89 verbose addNameRange registry:https://registry.npmjs.org/glob not in flight; fetching
90 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org
91 verbose request uri https://registry.npmjs.org/multer
92 verbose request no auth needed
93 info attempt registry request try #1 at 10:53:51 AM
94 http request GET https://registry.npmjs.org/multer
95 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org
96 verbose request uri https://registry.npmjs.org/glob
97 verbose request no auth needed
98 info attempt registry request try #1 at 10:53:51 AM
99 verbose etag "46WM8PKU1KH1CZRIDW01PZGF0"
100 http request GET https://registry.npmjs.org/glob
101 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org
102 info attempt registry request try #2 at 10:54:01 AM
103 http request GET https://registry.npmjs.org/image-size
104 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org
105 info attempt registry request try #2 at 10:54:01 AM
106 http request GET https://registry.npmjs.org/multer
107 info attempt registry request try #2 at 10:54:01 AM
108 verbose etag "46WM8PKU1KH1CZRIDW01PZGF0"
109 http request GET https://registry.npmjs.org/glob
110 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org
111 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org
112 info attempt registry request try #3 at 10:55:01 AM
113 http request GET https://registry.npmjs.org/image-size
114 info attempt registry request try #3 at 10:55:01 AM
115 http request GET https://registry.npmjs.org/multer
116 info attempt registry request try #3 at 10:55:01 AM
117 verbose etag "46WM8PKU1KH1CZRIDW01PZGF0"
118 http request GET https://registry.npmjs.org/glob
119 silly get cb [ 304, undefined ]
120 verbose etag https://registry.npmjs.org/glob from cache
121 verbose get saving glob to C:\Users\j.daft.adm\AppData\Roaming\npm-cache\registry.npmjs.org\glob\.cache.json
122 silly addNameRange number 2 { name: 'glob', range: '>=5.0.14 <6.0.0', hasData: true }
123 silly addNameRange versions [ 'glob',
123 silly addNameRange   [ '1.1.0',
123 silly addNameRange     '2.0.9',
123 silly addNameRange     '2.0.8',
123 silly addNameRange     '2.0.7',
123 silly addNameRange     '2.1.0',
123 silly addNameRange     '3.0.0',
123 silly addNameRange     '3.0.1',
123 silly addNameRange     '3.1.0',
123 silly addNameRange     '3.1.1',
123 silly addNameRange     '3.1.2',
123 silly addNameRange     '3.1.3',
123 silly addNameRange     '3.1.4',
123 silly addNameRange     '3.1.5',
123 silly addNameRange     '3.1.6',
123 silly addNameRange     '3.1.7',
123 silly addNameRange     '3.1.9',
123 silly addNameRange     '3.1.10',
123 silly addNameRange     '3.1.11',
123 silly addNameRange     '3.1.12',
123 silly addNameRange     '3.1.13',
123 silly addNameRange     '3.1.14',
123 silly addNameRange     '3.1.15',
123 silly addNameRange     '3.1.16',
123 silly addNameRange     '3.1.17',
123 silly addNameRange     '3.1.18',
123 silly addNameRange     '3.1.19',
123 silly addNameRange     '3.1.20',
123 silly addNameRange     '3.1.21',
123 silly addNameRange     '3.2.0',
123 silly addNameRange     '3.2.1',
123 silly addNameRange     '3.2.3',
123 silly addNameRange     '3.2.4',
123 silly addNameRange     '3.2.5',
123 silly addNameRange     '3.2.6',
123 silly addNameRange     '3.2.7',
123 silly addNameRange     '3.2.8',
123 silly addNameRange     '3.2.9',
123 silly addNameRange     '3.2.10',
123 silly addNameRange     '3.2.11',
123 silly addNameRange     '4.0.0',
123 silly addNameRange     '4.0.1',
123 silly addNameRange     '4.0.2',
123 silly addNameRange     '4.0.3',
123 silly addNameRange     '4.0.4',
123 silly addNameRange     '4.0.5',
123 silly addNameRange     '4.0.6',
123 silly addNameRange     '4.1.2-beta',
123 silly addNameRange     '4.1.2',
123 silly addNameRange     '4.1.3',
123 silly addNameRange     '4.1.4',
123 silly addNameRange     '4.1.5',
123 silly addNameRange     '4.1.6',
123 silly addNameRange     '4.2.0',
123 silly addNameRange     '4.2.1',
123 silly addNameRange     '4.2.2',
123 silly addNameRange     '4.3.0',
123 silly addNameRange     '4.3.1',
123 silly addNameRange     '4.3.2',
123 silly addNameRange     '4.3.3',
123 silly addNameRange     '4.3.4',
123 silly addNameRange     '4.3.5',
123 silly addNameRange     '4.4.0',
123 silly addNameRange     '4.4.2',
123 silly addNameRange     '4.5.0',
123 silly addNameRange     '5.0.0',
123 silly addNameRange     '4.5.1',
123 silly addNameRange     '5.0.1',
123 silly addNameRange     '4.5.2',
123 silly addNameRange     '5.0.2',
123 silly addNameRange     '4.5.3',
123 silly addNameRange     '5.0.3',
123 silly addNameRange     '5.0.4',
123 silly addNameRange     '5.0.5',
123 silly addNameRange     '5.0.6',
123 silly addNameRange     '5.0.7',
123 silly addNameRange     '5.0.9',
123 silly addNameRange     '5.0.10',
123 silly addNameRange     '5.0.11',
123 silly addNameRange     '5.0.12',
123 silly addNameRange     '5.0.13',
123 silly addNameRange     '5.0.14' ] ]
124 silly addNamed glob@5.0.14
125 verbose addNamed "5.0.14" is a plain semver version for glob
126 silly cache afterAdd glob@5.0.14
127 verbose afterAdd C:\Users\j.daft.adm\AppData\Roaming\npm-cache\glob\5.0.14\package\package.json not in flight; writing
128 verbose afterAdd C:\Users\j.daft.adm\AppData\Roaming\npm-cache\glob\5.0.14\package\package.json written
129 verbose stack Error: getaddrinfo ENOTFOUND registry.npmjs.org
129 verbose stack     at errnoException (dns.js:44:10)
129 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
130 verbose cwd c:\xampp\htdocs\openkb
131 error Windows_NT 6.3.9600
132 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
133 error node v0.12.7
134 error npm  v2.11.3
135 error code ENOTFOUND
136 error errno ENOTFOUND
137 error syscall getaddrinfo
138 error network getaddrinfo ENOTFOUND registry.npmjs.org
138 error network This is most likely not a problem with npm itself
138 error network and is related to network connectivity.
138 error network In most cases you are behind a proxy or have bad network settings.
138 error network
138 error network If you are behind a proxy, please make sure that the
138 error network 'proxy' config is set properly.  See: 'npm help config'
139 verbose exit [ 1, true 
```

I know network connection is fine as npm install commands are woking fine for other apps.
