### ISSUE TITLE
settings.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by berndlutz** [mrvautin/openKB#81]
I have just downloaded openKB. Changing the settings results in an error:

> settings.hasOwnProperty is not a function

It is viewed instead of the form after clicking on "update".

From the terminal:

```
TypeError: settings.hasOwnProperty is not a function
    at /www/openKB/routes/index.js:216:21
    at Layer.handle [as handle_request] (/www/openKB/node_modules/express/lib/router/layer.js:82:5)
    at next (/www/openKB/node_modules/express/lib/router/route.js:100:13)
    at Object.exports.check_login (/www/openKB/routes/common.js:75:3)
    at exports.restrict (/www/openKB/routes/common.js:66:10)
    at Layer.handle [as handle_request] (/www/openKB/node_modules/express/lib/router/layer.js:82:5)
    at next (/www/openKB/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/www/openKB/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/www/openKB/node_modules/express/lib/router/layer.js:82:5)
    at /www/openKB/node_modules/express/lib/router/index.js:234:24
```

**Comment by mrvautin** [comment]
What version of Node are you using?

**Comment by mrvautin** [comment]
Ignore my last comment. I will look into it.

**Comment by berndlutz** [comment]
Version v6.3.1

**Comment by mrvautin** [comment]
Wow. In Nodejs v6+ the `hasOwnProperty` has been removed. See fa8053404400c4223798e88ef18482acb8dcbb4a. I should really be testing more on Node v6.
