### ISSUE TITLE
MongoDB Upgrade Error

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#86]
```
webuser@****:~/adminkb$ npm run-script dbUpgrade

> openkb@1.0.16 dbUpgrade /home/*****/adminkb
> node data/mongodbUpgrade.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/home/******/adminkb/data/mongodbUpgrade.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/opt/node/bin/node" "/usr/local/bin/npm" "run-script" "dbUpgrade"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! openkb@1.0.16 dbUpgrade: `node data/mongodbUpgrade.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openkb@1.0.16 dbUpgrade script 'node data/mongodbUpgrade.                                                      js'.
npm ERR! This is most likely a problem with the openkb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node data/mongodbUpgrade.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls openkb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/******/adminkb/npm-debug.log
webuser@****:~/adminkb$
```

**Comment by thedaftbadger** [comment]
Not seeing the mongodbUpgrade.js file in the data folder

**Comment by mrvautin** [comment]
Good call! Whoops. I'm ignoring that entire folder. I will just fix .npmignore.

**Comment by thedaftbadger** [comment]
:) let me know when the fix is live and I'll try again

**Comment by thedaftbadger** [comment]
Worked perfectly!

**Comment by littleheart** [comment]
[root@skykb openKB]# npm run-script dbUpgrade

> openkb@1.0.23 dbUpgrade /var/www/html/openKB
> node data/mongodbUpgrade.js

undefined:28
            "connection_string": "mongodb://0.0.0.0:27017/skykbdb"
            ^

SyntaxError: Unexpected string in JSON at position 844
    at JSON.parse (<anonymous>)
    at Object.exports.read_config (/var/www/html/openKB/routes/common.js:34:31)
    at Object.<anonymous> (/var/www/html/openKB/data/mongodbUpgrade.js:16:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openkb@1.0.23 dbUpgrade: `node data/mongodbUpgrade.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openkb@1.0.23 dbUpgrade script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-22T14_52_15_896Z-debug.log
[root@skykb openKB]#
