### ISSUE TITLE
Bug - Config parse error

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#87]
Noticed this in the logs for the latest version.
```
Admin_KB-1 (err):     at Object.<anonymous> (/home/*****/adminkb/app.js:17:21)
Admin_KB-1 (err):     at Module._compile (module.js:435:26)
Admin_KB-1 (err):     at Object.Module._extensions..js (module.js:442:10)
Admin_KB-1 (err):     at Module.load (module.js:356:32)
Admin_KB-1 (err):     at Function.Module._load (module.js:311:12)
Admin_KB-1 (err):     at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
Admin_KB-1 (err):     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:46:21)
Admin_KB-1 (err):     at Module._compile (module.js:435:26)
Admin_KB-1 (err): SyntaxError: Unexpected token
Admin_KB-1 (err):
Admin_KB-1 (err):     at Object.parse (native)
Admin_KB-1 (err):     at Object.exports.read_config (/home/*****/adminkb/routes/common.js:11:17)
Admin_KB-1 (err):     at Object.<anonymous> (/home/*****/adminkb/app.js:17:21)
Admin_KB-1 (err):     at Module._compile (module.js:435:26)
Admin_KB-1 (err):     at Object.Module._extensions..js (module.js:442:10)
Admin_KB-1 (err):     at Module.load (module.js:356:32)
Admin_KB-1 (err):     at Function.Module._load (module.js:311:12)
Admin_KB-1 (err):     at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
Admin_KB-1 (err):     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:46:21)
Admin_KB-1 (err):     at Module._compile (module.js:435:26)
```

**Comment by mrvautin** [comment]
I think there is an issue with your config json. Are you able to check the json is not malformed in `/routes/config.js`?

**Comment by mrvautin** [comment]
TODO: Add some error catching around reading the config.

**Comment by mrvautin** [comment]
Did you solve this  @thedaftbadger? Was it a JSON issue?

**Comment by thedaftbadger** [comment]
Yes all solved 👍
